const workbook={source:'NW Char Builder.xlsx',sheets:JSON.parse(JSON.stringify(window.WORKBOOK_SHEETS||[]))};
let activeSheetIndex=1;
let showFormula=false;
let formulaTarget='';
let calcCache=new Map();
const app=document.getElementById('app');
const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const sheetLayouts={
  'DPS Template':{kind:'dps',gear:['A3','R10'],results:['A17','C23'],damage:['A13','B14'],buffs:['E13','I28'],classRace:['K13','O22'],misc:['Q13','R28']},
  'MSOD DPS Template':{kind:'dps',gear:['A3','R10'],results:['A17','C23'],damage:['A13','B14'],buffs:['E13','I28'],classRace:['K13','O22'],misc:['Q13','R28']},
  'HEAL Template':{kind:'heal',gear:['A3','R8'],results:['A11','C16'],buffs:['E11','I23'],classRace:['K11','L25'],misc:['N11','O23']},
  'TANK Template':{kind:'tank',gear:['A3','R9'],results:['A12','C18'],buffs:['E12','I24'],classRace:['K12','L24'],misc:['N12','O27']}
};
function colName(n){let s='';while(n){n--;s=letters[n%26]+s;n=Math.floor(n/26)}return s}
function colNum(col){let n=0;for(const ch of col){n=n*26+ch.charCodeAt(0)-64}return n}
function addrParts(addr){const m=String(addr).match(/^([A-Z]+)(\d+)$/);return{col:colNum(m[1]),row:Number(m[2])}}
function eachAddrInRange(ref){const[a,b]=ref.split(':');const A=addrParts(a),B=addrParts(b),out=[];for(let r=Math.min(A.row,B.row);r<=Math.max(A.row,B.row);r++){for(let c=Math.min(A.col,B.col);c<=Math.max(A.col,B.col);c++)out.push(colName(c)+r)}return out}
function rangeBounds(start,end){const A=addrParts(start),B=addrParts(end);return{r1:Math.min(A.row,B.row),r2:Math.max(A.row,B.row),c1:Math.min(A.col,B.col),c2:Math.max(A.col,B.col)}}
function getSheet(){return workbook.sheets[activeSheetIndex]}
function readCell(sheet,addr){return sheet.cells[addr]||{v:''}}
function asNumber(v){if(v===true)return 1;if(v===false)return 0;if(v===''||v==null)return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;const n=Number(v);return Number.isFinite(n)?n:0}
function displayValue(v){if(v===''||v==null)return'';if(v==='#ERR'||v==='#CYCLE')return v;if(typeof v==='number'){if(Math.abs(v-Math.round(v))<1e-10)return String(Math.round(v));return String(Math.round(v*1000000)/1000000)}return String(v)}
function isNumeric(v){return v!==''&&v!=null&&!Number.isNaN(Number(v))}
function evaluateCell(sheet,addr,stack=[]){const key=sheet.name+'!'+addr;if(calcCache.has(key))return calcCache.get(key);if(stack.includes(key))return'#CYCLE';const cell=readCell(sheet,addr);if(!cell.f)return cell.v??'';try{const val=evaluateFormula(sheet,cell.f,[...stack,key]);calcCache.set(key,val);return val}catch(err){return'#ERR'}}
function evaluateFormula(sheet,formula,stack){let f=String(formula).replace(/\r?\n/g,'').replace(/\s+/g,'');if(f.startsWith('='))f=f.slice(1);const ranges=[];f=f.replace(/\b([A-Z]{1,3}\d+):([A-Z]{1,3}\d+)\b/g,m=>{const token='__RANGE_'+ranges.length+'__';ranges.push(m);return token});f=f.replace(/\b([A-Z]{1,3}\d+)\b/g,m=>`cell("${m}")`);ranges.forEach((r,i)=>{f=f.replace('__RANGE_'+i+'__',`range("${r}")`)});f=f.replace(/\bSUM\(/gi,'SUM(').replace(/\bMIN\(/gi,'MIN(').replace(/\bROUND\(/gi,'ROUND(');const cell=a=>asNumber(evaluateCell(sheet,a,stack));const range=r=>eachAddrInRange(r).map(a=>asNumber(evaluateCell(sheet,a,stack)));const SUM=(...args)=>args.flat(Infinity).reduce((a,b)=>a+asNumber(b),0);const MIN=(...args)=>Math.min(...args.flat(Infinity).map(asNumber));const ROUND=(n,d=0)=>{const p=Math.pow(10,asNumber(d));return Math.round(asNumber(n)*p)/p};return Function('cell','range','SUM','MIN','ROUND',`return (${f});`)(cell,range,SUM,MIN,ROUND)}
function recalc(){calcCache=new Map();for(const sheet of workbook.sheets){for(const addr of Object.keys(sheet.cells)){const cell=sheet.cells[addr];if(cell.f)cell.calc=evaluateCell(sheet,addr,[])}}}
function valueAt(sheet,addr){const c=readCell(sheet,addr);return c.f?c.calc:c.v}
function cellClass(cell){if(cell.f)return'formula-field';if(typeof cell.v==='boolean')return'check-field';if(typeof cell.v==='string'&&cell.v.trim()!==''&&!isNumeric(cell.v))return'label-field';return'input-field'}
function canEdit(cell){if(cell.f)return false;if(typeof cell.v==='boolean')return true;if(typeof cell.v==='string'&&cell.v.trim()!==''&&!isNumeric(cell.v))return false;return true}
function updateCell(addr,value,type){const sheet=getSheet();if(!sheet.cells[addr])sheet.cells[addr]={v:''};if(type==='checkbox')sheet.cells[addr].v=Boolean(value);else{const v=String(value).trim();sheet.cells[addr].v=v===''?'':(!Number.isNaN(Number(v))?Number(v):v)}render()}
function render(){recalc();const sheet=getSheet();if(sheet.name==='README'){renderReadme(sheet);return}const layout=sheetLayouts[sheet.name]||sheetLayouts['DPS Template'];app.innerHTML=`${renderHeader(sheet,layout)}${renderTabs()}${renderToolbar()}${renderSummary(sheet,layout)}<main class="builder-layout"><section class="main-stack">${renderRangeCard(sheet,'Manual gear and stat bonuses','Type the ratings and every percentage bonus from each gear piece. Formula cells stay locked and update automatically.',layout.gear,'wide-table')}${layout.damage?renderRangeCard(sheet,'Damage estimator','Magnitude is editable. Average hit is calculated from the workbook formula.',layout.damage,'compact-table'):''}${renderRangeCard(sheet,'Self and team buffs','Use manual number fields and toggles exactly like the workbook.',layout.buffs,'compact-table')}</section><aside class="side-stack">${renderRangeCard(sheet,'Final results','These are calculated outputs from your manual inputs.',layout.results,'result-table')}${renderRangeCard(sheet,'Class and race toggles','Enable only the class/race options that apply to the current character.',layout.classRace,'compact-table')}${renderRangeCard(sheet,'Misc values','Manual values such as attributes, stamina, collars, Avian Aura count, and boon totals.',layout.misc,'compact-table')}</aside></main>`;bind()}
function renderHeader(sheet){return`<header class="topbar"><div><p class="eyebrow">Manual Neverwinter calculator</p><h1>${escapeHtml(sheet.name)}</h1><p class="sub">Cleaner web UI, same workbook behavior. Enter every bonus manually. Yellow result fields are calculated from the original Excel formulas.</p></div><div class="status-card"><span>Source</span><strong>${escapeHtml(workbook.source)}</strong><small>${Object.keys(sheet.cells).length} workbook cells loaded</small></div></header>`}
function renderTabs(){return`<nav class="tabs">${workbook.sheets.map((s,i)=>`<button class="${i===activeSheetIndex?'active':''}" data-sheet="${i}">${escapeHtml(s.name)}</button>`).join('')}</nav>`}
function renderToolbar(){return`<div class="toolbar"><button id="toggleFormula">${showFormula?'Show calculated values':'Show formulas'}</button><button id="exportBuild">Export JSON</button><label class="import-label">Import JSON<input id="importBuild" type="file" accept="application/json"></label><span class="hint">${formulaTarget?escapeHtml(formulaTarget):'Click any yellow formula field to see its original Excel formula.'}</span></div>`}
function renderSummary(sheet,layout){const b=rangeBounds(layout.results[0],layout.results[1]);let cards='';for(let r=b.r1+1;r<=b.r2;r++){const name=valueAt(sheet,'A'+r);const final=valueAt(sheet,'C'+r);if(name!==''&&final!=='')cards+=`<article class="metric"><span>${escapeHtml(displayValue(name))}</span><strong>${escapeHtml(displayValue(final))}%</strong><small>Final calculated value</small></article>`}return`<section class="summary-grid">${cards}</section>`}
function renderRangeCard(sheet,title,desc,range,type){return`<section class="section-card"><div class="section-head"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(desc)}</p></div></div><div class="table-scroll"><table class="manual-table ${type}">${renderRangeTable(sheet,range[0],range[1])}</table></div></section>`}
function renderRangeTable(sheet,start,end){const b=rangeBounds(start,end);let html='';for(let r=b.r1;r<=b.r2;r++){html+='<tr>';for(let c=b.c1;c<=b.c2;c++){const addr=colName(c)+r;const cell=readCell(sheet,addr);const cls=cellClass(cell);const val=cell.f?(showFormula?'='+cell.f:(cell.calc??'')):(cell.v??'');const tag=r===b.r1?'th':'td';html+=`<${tag} class="field ${cls}" data-addr="${addr}">`;html+=renderCellControl(addr,cell,val);html+=`</${tag}>`}html+='</tr>'}return html}
function renderCellControl(addr,cell,val){if(cell.f)return`<button class="formula-button" data-formula="${addr}"><span>${escapeHtml(displayValue(val))}</span><small>${addr}</small></button>`;if(typeof cell.v==='boolean')return`<label class="switch"><input type="checkbox" data-edit-check="${addr}" ${cell.v?'checked':''}><span></span></label>`;if(canEdit(cell))return`<input data-edit="${addr}" value="${escapeAttr(displayValue(val))}">`;return`<span class="label-text">${escapeHtml(displayValue(val))}</span>`}
function renderReadme(sheet){const lines=[];for(let r=1;r<=sheet.maxRow;r++){const v=valueAt(sheet,'A'+r);if(v)lines.push(`<li>${escapeHtml(displayValue(v))}</li>`)}app.innerHTML=`${renderHeader(sheet)}${renderTabs()}<main class="readme-card"><h2>Workbook instructions</h2><ol>${lines.join('')}</ol></main>`;bindTabsOnly()}
function bind(){bindTabsOnly();document.querySelectorAll('[data-edit]').forEach(input=>{input.addEventListener('change',()=>updateCell(input.dataset.edit,input.value,'text'));input.addEventListener('keydown',e=>{if(e.key==='Enter')input.blur()})});document.querySelectorAll('[data-edit-check]').forEach(input=>input.addEventListener('change',()=>updateCell(input.dataset.editCheck,input.checked,'checkbox')));document.querySelectorAll('[data-formula]').forEach(btn=>btn.addEventListener('click',()=>{const addr=btn.dataset.formula;const cell=readCell(getSheet(),addr);formulaTarget=`${getSheet().name}!${addr} = ${cell.f}`;render()}));document.getElementById('toggleFormula').onclick=()=>{showFormula=!showFormula;render()};document.getElementById('exportBuild').onclick=exportJson;document.getElementById('importBuild').onchange=importJson}
function bindTabsOnly(){document.querySelectorAll('[data-sheet]').forEach(btn=>btn.onclick=()=>{activeSheetIndex=Number(btn.dataset.sheet);formulaTarget='';render()})}
function exportJson(){const blob=new Blob([JSON.stringify(workbook,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='neverwinter-build.json';a.click();URL.revokeObjectURL(a.href)}
function importJson(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(imported.sheets){workbook.sheets=imported.sheets;activeSheetIndex=Math.min(activeSheetIndex,workbook.sheets.length-1);render()}else alert('Invalid workbook JSON')}catch(err){alert('Could not import JSON')}};reader.readAsText(file)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;')}
render();
